/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as IpoRouteImport } from './routes/ipo'
import { Route as GeopoliticsRouteImport } from './routes/geopolitics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRefreshTickersRouteImport } from './routes/api/public/refresh-tickers'
import { Route as ApiPublicIpoAlertsRouteImport } from './routes/api/public/ipo-alerts'
import { Route as ApiPublicIngestRssRouteImport } from './routes/api/public/ingest-rss'
import { Route as ApiPublicBackfillAiRouteImport } from './routes/api/public/backfill-ai'
import { Route as ApiPublicAskAiRouteImport } from './routes/api/public/ask-ai'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const IpoRoute = IpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => rootRouteImport,
} as any)
const GeopoliticsRoute = GeopoliticsRouteImport.update({
  id: '/geopolitics',
  path: '/geopolitics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshTickersRoute = ApiPublicRefreshTickersRouteImport.update({
  id: '/api/public/refresh-tickers',
  path: '/api/public/refresh-tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIpoAlertsRoute = ApiPublicIpoAlertsRouteImport.update({
  id: '/api/public/ipo-alerts',
  path: '/api/public/ipo-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRssRoute = ApiPublicIngestRssRouteImport.update({
  id: '/api/public/ingest-rss',
  path: '/api/public/ingest-rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillAiRoute = ApiPublicBackfillAiRouteImport.update({
  id: '/api/public/backfill-ai',
  path: '/api/public/backfill-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskAiRoute = ApiPublicAskAiRouteImport.update({
  id: '/api/public/ask-ai',
  path: '/api/public/ask-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/ipo': typeof IpoRoute
  '/policies': typeof PoliciesRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/ask-ai': typeof ApiPublicAskAiRoute
  '/api/public/backfill-ai': typeof ApiPublicBackfillAiRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/ipo-alerts': typeof ApiPublicIpoAlertsRoute
  '/api/public/refresh-tickers': typeof ApiPublicRefreshTickersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/ipo': typeof IpoRoute
  '/policies': typeof PoliciesRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/ask-ai': typeof ApiPublicAskAiRoute
  '/api/public/backfill-ai': typeof ApiPublicBackfillAiRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/ipo-alerts': typeof ApiPublicIpoAlertsRoute
  '/api/public/refresh-tickers': typeof ApiPublicRefreshTickersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/ipo': typeof IpoRoute
  '/policies': typeof PoliciesRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/watchlist': typeof WatchlistRoute
  '/api/public/ask-ai': typeof ApiPublicAskAiRoute
  '/api/public/backfill-ai': typeof ApiPublicBackfillAiRoute
  '/api/public/ingest-rss': typeof ApiPublicIngestRssRoute
  '/api/public/ipo-alerts': typeof ApiPublicIpoAlertsRoute
  '/api/public/refresh-tickers': typeof ApiPublicRefreshTickersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/geopolitics'
    | '/ipo'
    | '/policies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/watchlist'
    | '/api/public/ask-ai'
    | '/api/public/backfill-ai'
    | '/api/public/ingest-rss'
    | '/api/public/ipo-alerts'
    | '/api/public/refresh-tickers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/geopolitics'
    | '/ipo'
    | '/policies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/watchlist'
    | '/api/public/ask-ai'
    | '/api/public/backfill-ai'
    | '/api/public/ingest-rss'
    | '/api/public/ipo-alerts'
    | '/api/public/refresh-tickers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/geopolitics'
    | '/ipo'
    | '/policies'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/watchlist'
    | '/api/public/ask-ai'
    | '/api/public/backfill-ai'
    | '/api/public/ingest-rss'
    | '/api/public/ipo-alerts'
    | '/api/public/refresh-tickers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  GeopoliticsRoute: typeof GeopoliticsRoute
  IpoRoute: typeof IpoRoute
  PoliciesRoute: typeof PoliciesRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiPublicAskAiRoute: typeof ApiPublicAskAiRoute
  ApiPublicBackfillAiRoute: typeof ApiPublicBackfillAiRoute
  ApiPublicIngestRssRoute: typeof ApiPublicIngestRssRoute
  ApiPublicIpoAlertsRoute: typeof ApiPublicIpoAlertsRoute
  ApiPublicRefreshTickersRoute: typeof ApiPublicRefreshTickersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipo': {
      id: '/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof IpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geopolitics': {
      id: '/geopolitics'
      path: '/geopolitics'
      fullPath: '/geopolitics'
      preLoaderRoute: typeof GeopoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-tickers': {
      id: '/api/public/refresh-tickers'
      path: '/api/public/refresh-tickers'
      fullPath: '/api/public/refresh-tickers'
      preLoaderRoute: typeof ApiPublicRefreshTickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ipo-alerts': {
      id: '/api/public/ipo-alerts'
      path: '/api/public/ipo-alerts'
      fullPath: '/api/public/ipo-alerts'
      preLoaderRoute: typeof ApiPublicIpoAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-rss': {
      id: '/api/public/ingest-rss'
      path: '/api/public/ingest-rss'
      fullPath: '/api/public/ingest-rss'
      preLoaderRoute: typeof ApiPublicIngestRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-ai': {
      id: '/api/public/backfill-ai'
      path: '/api/public/backfill-ai'
      fullPath: '/api/public/backfill-ai'
      preLoaderRoute: typeof ApiPublicBackfillAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask-ai': {
      id: '/api/public/ask-ai'
      path: '/api/public/ask-ai'
      fullPath: '/api/public/ask-ai'
      preLoaderRoute: typeof ApiPublicAskAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  GeopoliticsRoute: GeopoliticsRoute,
  IpoRoute: IpoRoute,
  PoliciesRoute: PoliciesRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  WatchlistRoute: WatchlistRoute,
  ApiPublicAskAiRoute: ApiPublicAskAiRoute,
  ApiPublicBackfillAiRoute: ApiPublicBackfillAiRoute,
  ApiPublicIngestRssRoute: ApiPublicIngestRssRoute,
  ApiPublicIpoAlertsRoute: ApiPublicIpoAlertsRoute,
  ApiPublicRefreshTickersRoute: ApiPublicRefreshTickersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
